site_name: Расширения конфигурации 1С
site_url: https://tqm-systems.github.io/ConfigurationExtensions/
site_author: Maxim Samokhval

repo_name: TQM-SYSTEMS/ConfigurationExtensions
repo_url: https://github.com/TQM-SYSTEMS/ConfigurationExtensions
edit_uri: edit/main/docs

copyright: Copyright &copy; 2021 Maxim Samokhval

theme:
  name: mkdocs

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  language: ru
  features:
    - content.code.annotate
    - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
  palette:
    # Light mode
    - teal: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  # favicon: assets/favicon.png
  icon:
    logo: logo

plugins:
  - search:
      lang:
        - ru

extra:
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/TQM-SYSTEMS/ConfigurationExtensions"
    - icon: fontawesome/brands/telegram
      link: "https://t.me/tqmsystems"

extra_css:
  - "assets/stylesheets/extra.css"

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
# Page tree
nav:
  - Home: index.md
